# Jobs to build the client and server app for various architectures
name: Build

on:
  # Triggers the workflow on any push or pull request
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        distribution:
          - temurin
          - zulu
        java_version:
          - 11
          - 17

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Compile kotlin and build classes
        run: ./gradlew classes

      - name: Run code checks
        run: ./gradlew check
        continue-on-error: ${{ matrix.java_version == '17' }}

      - name: Run unit tests
        run: ./gradlew --no-build-cache cleanTest test tests:test
        continue-on-error: ${{ matrix.java_version == '17' }}

      - name: Build the Desktop app
        run: ./gradlew desktop:dist

      - name: Build the Java server
        run: ./gradlew server:dist

      - name: Build Android debug files
        continue-on-error: true
        run: |
          mkdir whatsNewDirectory
          echo "Nothing changed so far" > whatsNewDirectory/whatsnew-en-US
          ./gradlew :android:bundleDebug
          ./gradlew :android:assembleDebug

      - name: Print all known files for debugging
        run: find | sort
